### ISSUE TITLE
Javascript error in the main process

### ISSUE THREAD

**Issue by stromseng** [brunofin/cohesion#13]
Directly after install it seems to work fine, however after restarting the app, it now crashes.
When running the app i get the following:
```
Uncaught exception
TypeError: Error processing argument at index 0, conversion failure from undefined
at g.loadURL(node:electron/js2c/browser_init:165:8464)
at n.loadURL(node:electron/js2c/browser_init:33:1856)
at App.<anonymous>(/app/cohesion/resources/app.asar/dist/index:js:32:24)
at App.emit(node:events:539:35)
```

![image](https://github.com/brunofin/cohesion/assets/24990129/99da9a2a-6dbb-4780-a268-ba4f4dfe41c9)

Running NixOS using unstable branch.
Installed from flathub, using nix-flatpak.

**Comment by brunofin** [comment]
Damn I thought I solved this issue yesterday. Sorry about that. Do you
happen to know what version do you have installed? I know there's not yet
anywhere in the app that you can see it, but through gnome software you
could see what is the current version you have.

Please make sure you're running v1.0.5.

Regards,
Bruno Finger

**Comment by brunofin** [comment]
@stromseng could you please confirm whenever you have time if you are running the latest version from flathub and whether the problem still occurs for you? Thanks!

**Comment by stromseng** [comment]
Had a busy week. It seems i did not have the latest version installed. Thx for replying :)
