### ISSUE TITLE
Problem with last version

### ISSUE THREAD

**Issue by dedeweb** [brunofin/cohesion#21]
Hi ! 

The last version won't launch on my computer : 
```shell
flatpak run io.github.brunofin.Cohesion                                                                                                                                                     ✔  42s  
[3:0628/091530.082175:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
[3:0628/091530.296636:ERROR:ozone_platform_x11.cc(245)] Missing X server or $DISPLAY
[3:0628/091530.296674:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
/app/bin/cohesion: line 3:     3 Segmentation fault      (core dumped) zypak-wrapper.sh /app/cohesion/cohesion "$@"
```

Do you know why? 

I'm on Manjaro linux, wayland, and previous version was working well... 

Thanks

**Comment by brunofin** [comment]
hi, yes I am working on push a fix for this right now.
if you need a workaround while it's not updated on flathub, please use Flatseat and set the sockets as following:

Remove:
- socket=wayland
- socket=fallback-x11

Add:
- socket=x11

![image](https://github.com/brunofin/cohesion/assets/8077237/a9ee47d2-8f48-4b4b-b461-e4b5adc65d7f)

I am pushing this to flathub in a moment but it could take a couple of hours to be published. Sorry for the inconvenience.

**Comment by brunofin** [comment]
Related: #22

**Comment by brunofin** [comment]
Fix was just pushed to flathub, waiting for it to be published.

**Comment by dedeweb** [comment]
That was fast ! 
Thanks a lot, I upgraded from flathub, everything is working fine again :)
