### ISSUE TITLE
Is there a way to disable spell check?

### ISSUE THREAD

**Issue by wokawoka** [brunofin/cohesion#8]
I'm often writing texts in languages other than English and all the text is marked and underlined in red.
I couldn't find a way to disable spellcheck, and if cohesion is basically running notion in a sandboxed browser window, it would be great if there could be a way to change the spellcheck language.
Thank you very much for investing your time in this very useful application

**Comment by brunofin** [comment]
Thanks! Happy its useful!

Apparently it is possible to disable it. I'll look into also being able to
select other languages.

Leaving this for reference
https://electronjs.org/docs/latest/tutorial/spellchecker

**Comment by wokawoka** [comment]
Thank you very much for your reply.
I tried again to look for a setting to disable spell-check but couldn't find it in the options, both in the 'My settings' section and in the "Language & region" section.
Maybe I'm missing something.
Having the option to set a language other than English would be great, in the meantime could you suggest how to disable spell-check completely?
Thank you again!

**Comment by brunofin** [comment]
I added a new CLI argument to disable spellcheck via `--disable-spellcheck`. You can edit your .desktop file to make it permanent. If you have it setup to start with your session, you'll probably want to edit the one at `~/.config/autostart`.

In the future, I will add a menu item to disable spellcheck through the app, and to be able to select multiple languages to check spelling.

**Comment by wokawoka** [comment]
Great, thank you very much
I am looking forward to trying the new version and the new CLI argument as soon as it will be available on flathub.

**Comment by justresisting** [comment]
Spellcheck is on and shows the red lines for me but when i right click on it nothing happens. 

I understand that running cohesion with the argument --disable-spellcheck will turn the spellcheck off but what if I want to use the spellcheck feature?

Am I missing something super obvious?

Didn't want to open a new issue just to ask a dumb question, also wanted to let you know that cohesion has really been a great boost to using Notion on Linux, thank you for making it!!!

**Comment by belenos** [comment]
> I understand that running cohesion with the argument --disable-spellcheck will turn the spellcheck off but what if I want to use the spellcheck feature?
> 
> Am I missing something super obvious?

Same! I love the app, but I have dyslexia and spellcheck is an important accessibility feature for me.

**Comment by brunofin** [comment]
I'll have a look when possible

**Comment by wokawoka** [comment]
> I added a new CLI argument to disable spellcheck via `--disable-spellcheck`. You can edit your .desktop file to make it permanent. If you have it setup to start with your session, you'll probably want to edit the one at `~/.config/autostart`.
> 
> In the future, I will add a menu item to disable spellcheck through the app, and to be able to select multiple languages to check spelling.


I've just tried to launch cohesion multiple times with the command line argument  --disable-spellcheck but the spellchek is still active (last cohesion flatpak release).

Is the argument still supposed to work?
Thank you so much!

**Comment by Maraszynko** [comment]
same issue here, installed cohesion-git from aur and the --disable-spellcheck flag is not working properly

**Comment by threehappypenguins** [comment]
When I try the `--disable-spellcheck` flag, Cohesion won't open at all.

**Comment by brunofin** [comment]
FYI I am not the maintainer of the AUR package and I think it may be outdated there.
